#Makefile for 6D firmware 112

FW_VERSION=112
MODEL=6D
CANON_NAME_FIR=6D000112.FIR

# DryOSmemory map
# RESTARTSTART is selected to be just above the end of the bss
#
ROMBASEADDR		= 0xFF0C0000
RESTARTSTART	= 0x000D7900

include ../Makefile.installer
