#ifndef _cameraspecific_gui_h_
#define _cameraspecific_gui_h_

// SJE codes found for 200D:

// button codes as received by gui_main_task
#define BGMT_PRESS_UP 0x2a
#define BGMT_UNPRESS_UP 0x2b
#define BGMT_PRESS_DOWN 0x2c
#define BGMT_UNPRESS_DOWN 0x2d
#define BGMT_PRESS_LEFT 0x28
#define BGMT_UNPRESS_LEFT 0x29
#define BGMT_PRESS_RIGHT 0x26
#define BGMT_UNPRESS_RIGHT 0x27
#define BGMT_PRESS_SET 0x4
#define BGMT_UNPRESS_SET 0x5

#define BGMT_PLAY 0xb
#define BGMT_TRASH 0xd
#define BGMT_MENU 0 // very unsure, 0x62 maybe?
#define BGMT_INFO 0x7

#define BGMT_PRESS_DISP 0x8
#define BGMT_UNPRESS_DISP 0x9

// not yet found:
//#define BGMT_PRESS_UP_RIGHT 0x17
//#define BGMT_PRESS_UP_LEFT 0x18
//#define BGMT_PRESS_DOWN_RIGHT 0x1B
//#define BGMT_PRESS_DOWN_LEFT 0x1C

#define BGMT_UNPRESS_UDLR 0x15

//~ #define BGMT_Q 0x1E //Compatibility
//~ #define BGMT_Q_ALT 0x15 //Probably don't use 15 is generated by others
#define BGMT_PRESS_HALFSHUTTER 0x47
//#define BGMT_UNPRESS_HALFSHUTTER 0x48 // FIXME just this one button is defined in another file...
#define BGMT_PRESS_ZOOM_IN 0xe
#define BGMT_UNPRESS_ZOOM_IN 0xf
#define BGMT_PRESS_ZOOM_OUT 0x10
#define BGMT_UNPRESS_ZOOM_OUT 0x11
#define BGMT_PICSTYLE 0x13
#define BGMT_FUNC 0x12
#define BGMT_JOY_CENTER 0x0 // wrong, avoiding conflicting definition

#define BGMT_LV 0x1e

// wrong - avoiding conflicting definitions
#define BGMT_WHEEL_LEFT 77
#define BGMT_WHEEL_RIGHT 88
#define BGMT_WHEEL_UP 55
#define BGMT_WHEEL_DOWN 66

#define BGMT_FLASH_MOVIE 0
#define BGMT_PRESS_FLASH_MOVIE 0
#define BGMT_UNPRESS_FLASH_MOVIE 0

#define BGMT_ISO_MOVIE 0
#define BGMT_PRESS_ISO_MOVIE 0
#define BGMT_UNPRESS_ISO_MOVIE 0

#define GMT_OLC_INFO_CHANGED 59 // backtrace copyOlcDataToStorage call in gui_massive_event_loop

// needed for correct shutdown from powersave modes
#define GMT_GUICMD_START_AS_CHECK 43
#define GMT_GUICMD_OPEN_SLOT_COVER 40
#define GMT_GUICMD_LOCK_OFF 38

#define BTN_ZEBRAS_FOR_PLAYBACK BGMT_FUNC // what button to use for zebras in Play mode
#define BTN_ZEBRAS_FOR_PLAYBACK_NAME "FUNC"

//void GUI_SetLvMode(int);
//void GUI_SetMovieSize_a(int);
//void GUI_SetMovieSize_b(int);

#endif
