#define CONFIG_EARLY_PORT
//#define CONFIG_HELLO_WORLD

#define MEM_DEBUG
//#define CONFIG_NO_ADDITIONAL_VERSION
#define CONFIG_ADDITIONAL_VERSION
#define CONFIG_STATE_OBJECT_HOOKS
#define DEBUG_TASK_HOOK

#define CONFIG_NEW_DRYOS_TASK_HOOKS
#define CONFIG_NEW_TASK_STRUCTS
#define CONFIG_TASK_STRUCT_V2
#define CONFIG_TASK_ATTR_STRUCT_V2

#define CONFIG_DIGIC_IV

#define CONFIG_ALLOCATE_MEMORY_POOL
#define CONFIG_Q_MENU_PLAYBACK
#define CONFIG_4_3_SCREEN

#define CONFIG_LIVEVIEW
#define CONFIG_MOVIE
//#define FEATURE_FLASH_TWEAKS

// #undef CONFIG_MODULES
#define CONFIG_MENU_WITH_AV
