include $(TOP_DIR)/Makefile.setup

# should we define a platform for modules? for now use 'all' platform
PLATFORM_INC=$(TOP_DIR)/platform/all
CFLAGS += -DMODULE -DMODULE_NAME=$(MODULE_NAME) $(MODULE_CFLAGS)

MODULE_OUTPUT = $(MODULE_NAME).mo

all:: $(MODULE_OUTPUT)
clean::
	$(call build,CLEAN,$(RM) -f $(MODULE_OBJS) $(MODULE_OUTPUT) *.o *.d)

$(MODULE_OUTPUT): $(MODULE_OBJS)
	$(call build,MODULE,$(LD_REAL) -r -o $@ $^)

install::
	cp $(PWD)/$(MODULE_OUTPUT) $(CF_CARD_ML_DIR)/modules

FORCE: