MAKE=make
RM=rm
MV=mv
MKDIR=mkdir
CP=cp
export BIN_FILES=magiclantern magiclantern.bin autoexec.bin autoexec

BINARIES_PATH=binaries
LUA_PATH=$(TOP_DIR)/lua
PWD=$(shell pwd)
SRC_DIR=$(TOP_DIR)/src
PLATFORM_PATH=$(TOP_DIR)/platform
BUILDER_DIR=$(TOP_DIR)/../dumper
DOC_DIR=$(TOP_DIR)/doc
CROP_DIR=$(TOP_DIR)/cropmks
SCRIPT_DIR=$(TOP_DIR)/scripts
BIN_FILES=magiclantern magiclantern.bin autoexec.bin autoexec
