#!/bin/sh
#
# Partition table must have EOS_DEVELOP at offset 0x47
# and BOOTDISK at offset 0x5C.
#
# File to be loaded is AUTOEXEC.BIN
#
dev="$1"
if [ -z "$dev" ]; then
	dev=/dev/disk1s1
fi

echo EOS_DEVELOP | dd of="$dev" bs=1 seek=0x47 count=11
echo BOOTDISK | dd of="$dev" bs=1 seek=0x5C count=8
