
// Auto-generated; do not edit this file.
// Edit doc/menuindex.py instead.

#include "dryos.h"
#include "version.h"
#include "bmp.h"
#include "menu.h"
#include "menuhelp.h"

struct menu_entry help_menus[] = {
    {
        .name = "About Magic Lantern",
        .priv = 1,
        .select = menu_help_go_to_page,
        .display = menu_help_section_print,
    },
    {
        .name = "Important notes",
        .priv = 4,
        .select = menu_help_go_to_page,
        .display = menu_help_section_print,
    },
    {
        .name = "FAQ",
        .priv = 5,
        .select = menu_help_go_to_page,
        .display = menu_help_section_print,
    },
    {
        .name = "Known issues",
        .priv = 10,
        .select = menu_help_go_to_page,
        .display = menu_help_section_print,
    },
    {
        .name = "Keyboard shortcuts",
        .priv = 11,
        .select = menu_help_go_to_page,
        .display = menu_help_section_print,
    },
    {
        .name = "Menu options",
        .priv = 15,
        .select = menu_help_go_to_page,
        .display = menu_help_section_print,
    },
    {
        .name = "Extra info displays",
        .priv = 90,
        .select = menu_help_go_to_page,
        .display = menu_help_section_print,
    },
    {
        .name = "Power saving",
        .priv = 96,
        .select = menu_help_go_to_page,
        .display = menu_help_section_print,
    },
    {
        .name = "Hidden settings",
        .priv = 99,
        .select = menu_help_go_to_page,
        .display = menu_help_section_print,
    },
    {
        .name = "Epilogue",
        .priv = 100,
        .select = menu_help_go_to_page,
        .display = menu_help_section_print,
    },
};

static void
help_menu_init( void* unused )
{
	menu_add(" (i)", help_menus, COUNT(help_menus));
}

INIT_FUNC( "help_menu", help_menu_init );

int help_pages = 100;
int help_menus_num = 10;


