#include "all_features.h"

#define FEATURE_SILENT_PIC_HIRES
#define FEATURE_INTERMEDIATE_ISO_INTERCEPT_SCROLLWHEEL
#define FEATURE_AUTO_BURST_PICQ
#define FEATURE_LV_3RD_PARTY_FLASH
#define FEATURE_REC_NOTIFY_BEEP
