
# this is a very simple makefile for modules
TOP_DIR=../..

# define the module name - make sure name is max 8 characters
MODULE_NAME=adtg_gui
MODULE_OBJS=adtg_gui.o

# include modules environment
include $(TOP_DIR)/modules/Makefile.modules

