
TOP_DIR?=../..
ML_SETUP_EXTENSION=minimal
ML_SETUP_DISABLE_USER_CONFIGS = y
ML_SRC_PROFILE=minimal

include $(TOP_DIR)/platform/Makefile.platform.base

install:: autoexec.bin
	$(CP) autoexec.bin $(INSTALL_DIR)/

include $(TOP_DIR)/Makefile.inc
