# FIXME this module is broken.  Looks like it hasn't been able
# to build for a long time.  Not obvious how to fix.

# define the module name - make sure name is max 8 characters
MODULE_NAME = script
MODULE_OBJS = $(BUILD_DIR)/script.o
TOP_DIR = ../..

# include modules environment
include $(TOP_DIR)/modules/Makefile
.DEFAULT_GOAL := $(BUILD_DIR)/module_complete
