Found 134 stubs in ./stubs-1100D.104.S.
NSTUB(0xFF1E8B94, AcquireRecursiveLock)           // might be good (dumps=1, score=14)
NSTUB(0xFF07096C, AllocateMemory)                 // might be good (dumps=1, score=1.7e+02)
NSTUB(0xFF31CAD8, CreateDialogBox)                // might be good (dumps=1, score=74)
NSTUB(0xFF073A7C, CreateRecursiveLock)            // might be good (dumps=1, score=5.6)
NSTUB(0xFF06C914, DebugMsg)                       // might be good (dumps=1, score=1.1e+03)
NSTUB(0xFF31C270, DeleteDialogBox)                // might be good (dumps=1, score=47)
NSTUB(0xFF1D48C8, EngDrvOut)                      // might be good (dumps=1, score=61)
NSTUB(0xFF1DA5F0, FIO_CleanupAfterFindNext_maybe) // might be good (dumps=1, score=69)
NSTUB(0xFF1D9620, FIO_CloseFile)                  // might be good (dumps=1, score=1e+02)
NSTUB(0xFF1D9E5C, FIO_CreateDirectory)            // might be good (dumps=1, score=13)
NSTUB(0xFF1D927C, FIO_CreateFile)                 // might be good (dumps=1, score=50)
NSTUB(0xFF1DA41C, FIO_FindFirstEx)                // might be good (dumps=1, score=50)
NSTUB(0xFF1DA510, FIO_FindNextEx)                 // might be good (dumps=1, score=50)
NSTUB(0xFF1D979C, FIO_GetFileSize)                // might be good (dumps=1, score=92)
NSTUB(0xFF1D91C0, FIO_Open)                       // might be good (dumps=1, score=92)
NSTUB(0xFF1D93D0, FIO_ReadFile)                   // might be good (dumps=1, score=87)
NSTUB(0xFF1D9328, FIO_RemoveFile)                 // might be good (dumps=1, score=53)
NSTUB(0xFF1D9570, FIO_WriteFile)                  // might be good (dumps=1, score=65)
NSTUB(0xFF070CFC, FreeMemory)                     // might be good (dumps=1, score=1.6e+02)
NSTUB(0xFF020DFC, GUI_Control)                    // might be good (dumps=1, score=26)
NSTUB(0xFF223218, GUI_GetFirmVersion)             // might be good (dumps=1, score=11)
NSTUB(0xFF510C1C, GetCFnData)                     // might be good (dumps=1, score=19)
NSTUB(0xFF070710, GetMemoryInformation)           // might be good (dumps=1, score=6.4)
NSTUB(0xFF3714A4, HideUnaviFeedBack_maybe)        // might be good (dumps=1, score=1.2)
NSTUB(       0x0, LCD_Palette)                    // no match
NSTUB(       0x0, LiveViewApp_handler)            // no match
NSTUB(       0x0, LiveViewApp_handler_BL_JudgeBottomInfoDispTimerState) // no match
NSTUB(0xFF377C44, LiveViewApp_handler_end)        // might be good (dumps=1, score=9.3)
NSTUB(0xFF0694E4, LoadCalendarFromRTC)            // might be good (dumps=1, score=30)
NSTUB(0xFF337C2C, MirrorDisplay)                  // might be good (dumps=1, score=3.4)
NSTUB(0xFF1DC754, MuteOff_0)                      // might be good (dumps=1, score=0.47)
NSTUB(0xFF1DC70C, MuteOn_0)                       // might be good (dumps=1, score=0.46)
NSTUB(0xFF337C8C, NormalDisplay)                  // might be good (dumps=1, score=3.4)
NSTUB(0xFF13ACC4, PtpPropButtonSW1)               // might be good (dumps=1, score=3.2)
NSTUB(0xFF13AD68, PtpPropButtonSW2)               // might be good (dumps=1, score=3.2)
NSTUB(0xFF1E8CA8, ReleaseRecursiveLock)           // might be good (dumps=1, score=14)
NSTUB(0xFF139A00, RemoteRelease)                  // might be good (dumps=1, score=3.8)
NSTUB(0xFF337C5C, ReverseDisplay)                 // might be good (dumps=1, score=3.4)
NSTUB(0xFF062AF4, SetBitmapVramAddress)           // might be good (dumps=1, score=8.2)
NSTUB(0xFF510E48, SetCFnData)                     // might be good (dumps=1, score=19)
NSTUB(0xFF0699F4, _audio_ic_read)                 // might be good (dumps=1, score=4.6)
NSTUB(0xFF069B38, _audio_ic_write)                // might be good (dumps=1, score=24)
NSTUB(0xFF05BBE4, _prop_cleanup)                  // might be good (dumps=1, score=42)
NSTUB(       0x0, additional_version)             // no match
NSTUB(0xFF1EFE08, alloc_dma_memory)               // might be good (dumps=1, score=91)
NSTUB(0xFF4C4674, audio_thresholds)               // Good. Found matches: ff4c4674/36, ff4c4664/4.7
NSTUB(       0x0, bmp_vram_info)                  // no match
NSTUB(0xFF06C548, bootdisk_disable)               // might be good (dumps=1, score=1.3)
NSTUB(0xFF06C53C, bootdisk_enable)                // might be good (dumps=1, score=1.3)
NSTUB(0xFF530984, bzero32)                        // might be good (dumps=1, score=1.5e+02)
NSTUB(0xFF06D7DC, call)                           // might be good (dumps=1, score=1.3e+02)
NSTUB(       0x0, camera_engine)                  // no match
NSTUB(0xFF4C2CD8, cfReadBlk)                      // might be good (dumps=1, score=9.1)
NSTUB(       0x0, cf_device)                      // no match
NSTUB(0xFF010500, cli_save)                       // might be good (dumps=1, score=0.32)
NSTUB(0xFF017F80, create_init_task)               // might be good (dumps=1, score=3.1)
NSTUB(0xFF06F40C, create_named_semaphore)         // might be good (dumps=1, score=81)
NSTUB(0xFF011028, cstart)                         // might be good (dumps=1, score=1.6)
NSTUB(0xFF31B4A0, ctrlman_dispatch_event)         // might be good (dumps=1, score=10)
NSTUB(0xFF31D3EC, dialog_redraw)                  // might be good (dumps=1, score=78)
NSTUB(0xFF2277E8, dialog_set_property_str)        // might be good (dumps=1, score=54)
NSTUB(0xFF1DC10C, dispcheck)                      // might be good (dumps=1, score=6)
NSTUB(       0x0, dm_names)                       // no match
NSTUB(0xFF06CC74, dm_set_store_level)             // might be good (dumps=1, score=15)
NSTUB(0xFF06C894, dmstart)                        // might be good (dumps=1, score=7.9)
NSTUB(0xFF06C8D4, dmstop)                         // might be good (dumps=1, score=7.9)
NSTUB(0xFF06D2B4, dumpf)                          // might be good (dumps=1, score=3.9)
NSTUB(0xFF1D4C8C, engio_write)                    // might be good (dumps=1, score=77)
NSTUB(0xFF018D8C, free)                           // might be good (dumps=1, score=14)
NSTUB(0xFF1EFE3C, free_dma_memory)                // might be good (dumps=1, score=80)
NSTUB(0xFF41686C, fsuDecodePartitionTable)        // might be good (dumps=1, score=2.1)
NSTUB(0xFF0175F4, get_current_task)               // might be good (dumps=1, score=11)
NSTUB(0xFF06F654, give_semaphore)                 // might be good (dumps=1, score=1e+02)
NSTUB(       0x0, gui_change_lcd_state_post)      // no match
NSTUB(0xFF0A7420, gui_change_mode)                // might be good (dumps=1, score=10)
NSTUB(       0x0, gui_change_shoot_type_post)     // no match
NSTUB(0xFF02144C, gui_init_end)                   // might be good (dumps=1, score=4.2)
NSTUB(       0x0, gui_init_event)                 // no match
NSTUB(0xFF0A7B90, gui_local_post)                 // might be good (dumps=1, score=3.2)
NSTUB(0xFF139910, gui_lock)                       // might be good (dumps=1, score=23)
NSTUB(       0x0, gui_main_struct)                // no match
NSTUB(0xFF020A40, gui_main_task)                  // might be good (dumps=1, score=5.5)
NSTUB(       0x0, gui_massive_event_loop)         // no match
NSTUB(0xFF0A8128, gui_other_post)                 // might be good (dumps=1, score=0.99)
NSTUB(       0x0, gui_post_10000085)              // no match
NSTUB(0xFF31B5F0, gui_task_create)                // might be good (dumps=1, score=9.4)
NSTUB(0xFF31B710, gui_task_destroy)               // might be good (dumps=1, score=18)
NSTUB(       0x0, gui_task_list)                  // no match
NSTUB(       0x0, gui_timer_something)            // no match
NSTUB(       0x0, gui_timer_struct)               // no match
NSTUB(       0x0, hotplug_struct)                 // no match
NSTUB(0xFF01B2CC, hotplug_task)                   // might be good (dumps=1, score=11)
NSTUB(       0x0, hotplug_usb_buf)                // no match
NSTUB(0xFF0197D8, init_task)                      // might be good (dumps=1, score=10)
NSTUB(       0x0, lv_path_struct)                 // no match
NSTUB(0xFF018D34, malloc)                         // might be good (dumps=1, score=11)
NSTUB(0xFF530890, memcpy)                         // might be good (dumps=1, score=1.5e+02)
NSTUB(0xFF1E885C, msg_queue_receive)              // might be good (dumps=1, score=24)
NSTUB(0xFF06FA40, msleep)                         // might be good (dumps=1, score=1.1e+02)
NSTUB(0xFF1B9544, mvrFixQScale)                   // might be good (dumps=1, score=4.8)
NSTUB(0xFF1B9020, mvrSetDefQScale)                // might be good (dumps=1, score=4.7)
NSTUB(0xFF1B9058, mvrSetFullHDOptSize)            // might be good (dumps=1, score=4.9)
NSTUB(0xFF1B9248, mvrSetGopOptSizeFULLHD)         // might be good (dumps=1, score=4.7)
NSTUB(0xFF1B92CC, mvrSetGopOptSizeHD)             // might be good (dumps=1, score=4.7)
NSTUB(0xFF1B9344, mvrSetGopOptSizeVGA)            // might be good (dumps=1, score=4.7)
NSTUB(0xFF1B91B8, mvrSetHDOptSize)                // might be good (dumps=1, score=4.9)
NSTUB(0xFF1B9564, mvrSetPrintMovieLog)            // might be good (dumps=1, score=4.8)
NSTUB(0xFF1B8F50, mvrSetQscale)                   // might be good (dumps=1, score=4.7)
NSTUB(0xFF1B9200, mvrSetVGAOptSize)               // might be good (dumps=1, score=4.9)
NSTUB(       0x0, mvr_config)                     // no match
NSTUB(0xFF06E260, oneshot_timer)                  // might be good (dumps=1, score=31)
NSTUB(0xFF05BA3C, prop_deliver)                   // might be good (dumps=1, score=44)
NSTUB(0xFF05BC7C, prop_get_value)                 // might be good (dumps=1, score=62)
NSTUB(0xFF05BAC4, prop_register_slave)            // might be good (dumps=1, score=39)
NSTUB(0xFF05B45C, prop_request_change)            // might be good (dumps=1, score=1.7e+02)
NSTUB(0xFF223844, prop_request_icu_auto_poweroff) // might be good (dumps=1, score=68)
NSTUB(0xFF2A35D4, ptp_register_handler)           // might be good (dumps=1, score=38)
NSTUB(0xFF1EDA10, register_func)                  // Good. Found matches: ff1eda10/1.2e+02, ff1eda20/6.2
NSTUB(0xFF4C8A1C, sdReadBlk)                      // might be good (dumps=1, score=9.2)
NSTUB(       0x0, sd_device)                      // no match
NSTUB(0xFF010514, sei_restore)                    // might be good (dumps=1, score=0.22)
NSTUB(0xFF1D47B8, shamem_read)                    // might be good (dumps=1, score=10)
NSTUB(       0x0, sounddev)                       // no match
NSTUB(       0x0, sounddev_active_in)             // no match
NSTUB(0xFF057570, sounddev_task)                  // might be good (dumps=1, score=8.2)
NSTUB(0xFF201F08, strcpy)                         // might be good (dumps=1, score=1.3e+02)
NSTUB(0xFF06F56C, take_semaphore)                 // might be good (dumps=1, score=1.5e+02)
NSTUB(0xFF06FAF4, task_create)                    // might be good (dumps=1, score=23)
NSTUB(       0x0, task_dispatch_hook)             // no match
NSTUB(0xFF07C970, task_trampoline)                // might be good (dumps=1, score=0.5)
NSTUB(0xFF2E0164, vram_get_number)                // might be good (dumps=1, score=12)
NSTUB(       0x0, vram_get_pos_and_size)          // no match
NSTUB(       0x0, vram_info)                      // no match
NSTUB(0xFF1EBFE0, vsnprintf)                      // might be good (dumps=1, score=9.5)
