// Then, start with a tiny feature set

/** Overlay menu **/

#define FEATURE_GLOBAL_DRAW
#define FEATURE_ZEBRA
#define FEATURE_ZEBRA_FAST
#define FEATURE_FOCUS_PEAK
#define FEATURE_MAGIC_ZOOM
#define FEATURE_CROPMARKS
#define FEATURE_SPOTMETER
#define FEATURE_FALSE_COLOR
#define FEATURE_HISTOGRAM
#define FEATURE_WAVEFORM
#define FEATURE_VECTORSCOPE
/*-------------------*/

#define CONFIG_LV_FOCUS_INFO

/** Movie menu **/
#define FEATURE_REC_INDICATOR
#define FEATURE_MOVIE_LOGGING
#define FEATURE_NITRATE
#define FEATURE_FPS_OVERRIDE


/** Shoot menu **/
#define FEATURE_INTERVALOMETER
#define FEATURE_BULB_TIMER
#define FEATURE_SILENT_PIC
#define FEATURE_FLASH_TWEAKS
#define FEATURE_WHITE_BALANCE
#define FEATURE_EXPO_ISO
#define FEATURE_EXPO_ISO_HTP
#define FEATURE_EXPO_ISO_DIGIC
#define FEATURE_EXPO_SHUTTER
#define FEATURE_EXPO_APERTURE


/** Display menu **/
#define FEATURE_LV_BRIGHTNESS_CONTRAST
#define FEATURE_LV_SATURATION
#define FEATURE_LV_DISPLAY_GAIN
#define FEATURE_COLOR_SCHEME
#define FEATURE_CLEAR_OVERLAYS



#define FEATURE_SCREENSHOT
#define FEATURE_SCREENSHOT_422

#define FEATURE_DONT_CLICK_ME

#define FEATURE_SHOW_TASKS
#define FEATURE_SHOW_CPU_USAGE

#define FEATURE_SHOW_IMAGE_BUFFERS_INFO
#define FEATURE_SHOW_FREE_MEMORY
#define FEATURE_SHOW_SHUTTER_COUNT

