// First try to print Hello World



//~ #define CONFIG_HELLO_WORLD

// Then, start with a tiny feature set

#define FEATURE_GLOBAL_DRAW
#define FEATURE_ZEBRA
#define FEATURE_HISTOGRAM
#define FEATURE_INTERVALOMETER




#define FEATURE_SCREENSHOT
#define FEATURE_SCREENSHOT_422

#define FEATURE_DONT_CLICK_ME

#define FEATURE_SHOW_TASKS
#define FEATURE_SHOW_CPU_USAGE

#define FEATURE_SHOW_IMAGE_BUFFERS_INFO
#define FEATURE_SHOW_FREE_MEMORY
#define FEATURE_SHOW_SHUTTER_COUNT

#define FEATURE_WHITE_BALANCE
#define FEATURE_EXPO_ISO
#define FEATURE_EXPO_ISO_HTP
#define FEATURE_EXPO_ISO_DIGIC
#define FEATURE_EXPO_SHUTTER
#define FEATURE_EXPO_APERTURE