
# this is a very simple makefile for modules
TOP_DIR=../..

# define the module name - make sure name is max 8 characters
MODULE_NAME=xml_cfg
MODULE_OBJS=xml_cfg.o mxml-src/mxml-attr.o mxml-src/mxml-entity.o mxml-src/mxml-file.o mxml-src/mxml-get.o mxml-src/mxml-index.o mxml-src/mxml-node.o mxml-src/mxml-search.o mxml-src/mxml-set.o mxml-src/mxml-private.o mxml-src/mxml-string.o

# include modules environment
include $(TOP_DIR)/modules/Makefile.modules

CFLAGS += 

