#include "platform.h"

#include "table.c"
#include "lex.c"
#include "parse.c"
#include "expression.c"
#include "heap.c"
#include "type.c"
#include "variable.c"
#include "clibrary.c"
#include "platform.c"
#include "include.c"
#include "platform_ml.c"
#include "library_ml.c"
