#include "all_features.h"

#define FEATURE_LV_3RD_PARTY_FLASH
#define FEATURE_EYEFI_TRICKS

// Disable all audio stuff
#undef FEATURE_WAV_RECORDING
#undef FEATURE_FPS_WAV_RECORD
#undef FEATURE_BEEP
#undef FEATURE_VOICE_TAGS
#undef FEATURE_AUDIO_REMOTE_SHOT
#undef FEATURE_AUDIO_METERS

#undef FEATURE_AUTO_BURST_PICQ // maybe not working on 650D

// No DISP button
#undef FEATURE_OVERLAYS_IN_PLAYBACK_MODE
#undef FEATURE_ARROW_SHORTCUTS

// Not working :(
#undef FEATURE_IMAGE_EFFECTS 
#undef FEATURE_DEFISHING_PREVIEW
#undef FEATURE_ANAMORPHIC_PREVIEW

#undef FEATURE_LV_BUTTON_PROTECT
#undef FEATURE_LV_BUTTON_RATE

#undef FEATURE_MOVIE_RESTART
#undef FEATURE_WARNINGS_FOR_BAD_SETTINGS

#undef FEATURE_TRAP_FOCUS

// Glitchy
#undef FEATURE_STICKY_DOF
#undef FEATURE_STICKY_HALFSHUTTER

// Only if PROPS are off
#ifndef CONFIG_PROP_REQUEST_CHANGE
#warning "PROP REQUEST CHANGE IS OFF - DISABLING SOME FEATURES"
#undef FEATURE_WHITE_BALANCE
#undef FEATURE_EXPO_ISO
#undef FEATURE_EXPO_ISO_HTP
#undef FEATURE_EXPO_ISO_DIGIC
#undef FEATURE_EXPO_SHUTTER
#undef FEATURE_EXPO_APERTURE
#undef FEATURE_PICSTYLE
#undef FEATURE_REC_PICSTYLE
#undef FEATURE_EXPO_LOCK
#undef FEATURE_EXPO_PRESET
#undef FEATURE_EXPO_OVERRIDE
#undef FEATURE_LV_ZOOM_SETTINGS
#undef FEATURE_LV_FOCUS_BOX_FAST
#undef FEATURE_LV_FOCUS_BOX_SNAP
#undef FEATURE_SHUTTER_LOCK
#undef FEATURE_HDR_BRACKETING
#undef FEATURE_BULB_RAMPING
#undef FEATURE_GRADUAL_EXPOSURE
#undef FEATURE_FOLLOW_FOCUS
#undef FEATURE_RACK_FOCUS
#undef FEATURE_FOCUS_STACKING
#undef FEATURE_AF_PATTERNS
#endif

#define FEATURE_INTERMEDIATE_ISO_PHOTO_DISPLAY
