#include "all_features.h"

#define FEATURE_LV_3RD_PARTY_FLASH
#define FEATURE_EYEFI_TRICKS

// Disable all audio stuff
#undef FEATURE_WAV_RECORDING
#undef FEATURE_FPS_WAV_RECORD
#undef FEATURE_BEEP
#undef FEATURE_VOICE_TAGS
#undef FEATURE_AUDIO_REMOTE_SHOT
#undef FEATURE_AUDIO_METERS

#undef FEATURE_AUTO_BURST_PICQ // maybe not working on 650D

// No DISP button
#undef FEATURE_OVERLAYS_IN_PLAYBACK_MODE
#undef FEATURE_ARROW_SHORTCUTS
#undef FEATURE_IMAGE_EFFECTS // none working

#define FEATURE_INTERMEDIATE_ISO_PHOTO_DISPLAY
