/*
 * Just a copy of the 650D stuff. Indented = WRONG
 */

#include "all_features.h"

//~ #define FEATURE_LV_3RD_PARTY_FLASH // requires props
#define FEATURE_EYEFI_TRICKS

// Disable all audio stuff
#undef FEATURE_WAV_RECORDING
#undef FEATURE_FPS_WAV_RECORD
#undef FEATURE_BEEP
#undef FEATURE_VOICE_TAGS
#undef FEATURE_AUDIO_REMOTE_SHOT
#undef FEATURE_AUDIO_METERS


#undef FEATURE_ARROW_SHORTCUTS

// Not working :(
#undef FEATURE_NITRATE
#undef FEATURE_IMAGE_EFFECTS
#undef FEATURE_DEFISHING_PREVIEW
#undef FEATURE_ANAMORPHIC_PREVIEW

#undef FEATURE_LV_BUTTON_PROTECT
#undef FEATURE_LV_BUTTON_RATE

#undef FEATURE_TRAP_FOCUS
#undef FEATURE_FLEXINFO

// Glitchy
#undef FEATURE_STICKY_DOF
#undef FEATURE_STICKY_HALFSHUTTER
//~ #undef FLEXINFO_DEVELOPER_MENU - disable from flexinfo.h

#define FEATURE_INTERMEDIATE_ISO_PHOTO_DISPLAY
//~ #define FEATURE_SHOW_SIGNATURE
//~ #define FEATURE_SHOW_STATE_FPS
#define FEATURE_FOCUS_PEAK_DISP_FILTER

//edit by Science
#undef CONFIG_STATE_OBJECT_HOOKS


// DISABLE JUST ABOUT EVERYTHING, UNTIL VALUES ARE VERIFIED
#undef FEATURE_ANALOG_GAIN
#undef FEATURE_DIGITAL_GAIN
#undef FEATURE_AGC_TOGGLE
#undef FEATURE_WIND_FILTER
#undef FEATURE_INPUT_SOURCE
#undef FEATURE_MIC_POWER
#undef FEATURE_HEADPHONE_MONITORING
#undef FEATURE_HEADPHONE_OUTPUT_VOLUME
#undef FEATURE_AUDIO_METERS
#undef FEATURE_BEEP
#undef FEATURE_WAV_RECORDING
#undef FEATURE_VOICE_TAGS
#undef FEATURE_EXPO_ISO_DIGIC
#undef FEATURE_WHITE_BALANCE
#undef FEATURE_EXPO_ISO
#undef FEATURE_EXPO_ISO_HTP
#undef FEATURE_EXPO_SHUTTER
#undef FEATURE_EXPO_APERTURE
#undef FEATURE_INTERMEDIATE_ISO_PHOTO_DISPLAY
#undef FEATURE_INTERMEDIATE_ISO_INTERCEPT_SCROLLWHEEL
#undef FEATURE_PICSTYLE
#undef FEATURE_REC_PICSTYLE
#undef FEATURE_EXPO_LOCK
#undef FEATURE_EXPO_PRESET
#undef FEATURE_EXPSIM
#undef FEATURE_EXPO_OVERRIDE
#undef FEATURE_GLOBAL_DRAW
#undef FEATURE_ZEBRA
#undef FEATURE_ZEBRA_FAST
#undef FEATURE_FOCUS_PEAK
#undef FEATURE_FOCUS_PEAK_DISP_FILTER
#undef FEATURE_MAGIC_ZOOM
#undef FEATURE_MAGIC_ZOOM_FULL_SCREEN
#undef FEATURE_CROPMARKS
#undef FEATURE_GHOST_IMAGE
#undef FEATURE_SPOTMETER
#undef FEATURE_FALSE_COLOR
#undef FEATURE_HISTOGRAM
#undef FEATURE_WAVEFORM
#undef FEATURE_VECTORSCOPE
#undef FEATURE_OVERLAYS_IN_PLAYBACK_MODE
#undef FEATURE_RAW_HISTOGRAM
#undef FEATURE_RAW_SPOTMETER
#undef FEATURE_RAW_ZEBRAS
#undef FEATURE_NITRATE
#undef FEATURE_NITRATE_WAV_RECORD
#undef FEATURE_VIDEO_HACKS
#undef FEATURE_REC_INDICATOR
#undef FEATURE_MOVIE_LOGGING
#undef FEATURE_MOVIE_RESTART
#undef FEATURE_MOVIE_AUTOSTOP_RECORDING
#undef FEATURE_REC_NOTIFY
#undef FEATURE_REC_NOTIFY_BEEP
#undef FEATURE_MOVIE_REC_KEY
#undef FEATURE_FORCE_LIVEVIEW
#undef FEATURE_SHUTTER_LOCK
#undef FEATURE_GRADUAL_EXPOSURE
#undef FEATURE_FPS_OVERRIDE
#undef FEATURE_FPS_RAMPING
#undef FEATURE_FPS_WAV_RECORD
#undef FEATURE_HDR_VIDEO
#undef FEATURE_HDR_EXTENDED
#undef FEATURE_IMAGE_EFFECTS
#undef FEATURE_VIGNETTING_CORRECTION
#undef FEATURE_SHUTTER_FINE_TUNING
#undef FEATURE_MOVIE_RECORDING_50D
#undef FEATURE_LVAE_EXPO_LOCK
#undef FEATURE_CROP_MODE_HACK
#undef FEATURE_HDR_BRACKETING
#undef FEATURE_INTERVALOMETER
#undef FEATURE_INTERVALOMETER_MOVIE
#undef FEATURE_FOCUS_RAMPING
#undef FEATURE_BULB_TIMER
#undef FEATURE_BULB_TIMER_SHOW_PREVIOUS_PIC
#undef FEATURE_LCD_SENSOR_REMOTE
#undef FEATURE_LCD_SENSOR_SHORTCUTS
#undef FEATURE_AUDIO_REMOTE_SHOT
#undef FEATURE_MOTION_DETECT
#undef FEATURE_MLU
#undef FEATURE_MLU_HANDHELD
#undef FEATURE_MLU_HANDHELD_DEBUG
#undef FEATURE_MLU_DIRECT_PRINT_SHORTCUT
#undef FEATURE_FLASH_TWEAKS
#undef FEATURE_FLASH_NOFLASH
#undef FEATURE_LV_3RD_PARTY_FLASH
#undef FEATURE_PICQ_DANGEROUS
#undef FEATURE_SNAP_SIM
#undef FEATURE_TRAP_FOCUS
#undef FEATURE_FOLLOW_FOCUS
#undef FEATURE_RACK_FOCUS
#undef FEATURE_FOCUS_STACKING
#undef FEATURE_AF_PATTERNS
#undef FEATURE_MOVIE_AF
#undef FEATURE_DIGIC_FOCUS_PEAKING
#undef FEATURE_LV_BRIGHTNESS_CONTRAST
#undef FEATURE_LV_SATURATION
#undef FEATURE_LV_CRAZY_COLORS
#undef FEATURE_LV_DISPLAY_GAIN
#undef FEATURE_COLOR_SCHEME
#undef FEATURE_CLEAR_OVERLAYS
#undef FEATURE_DEFISHING_PREVIEW
#undef FEATURE_ANAMORPHIC_PREVIEW
#undef FEATURE_LEVEL_INDICATOR
#undef FEATURE_SCREEN_LAYOUT
#undef FEATURE_IMAGE_POSITION
#undef FEATURE_UPSIDE_DOWN
#undef FEATURE_IMAGE_ORIENTATION
#undef FEATURE_AUTO_MIRRORING_HACK
#undef FEATURE_FORCE_HDMI_VGA
#undef FEATURE_DISPLAY_SHAKE
#undef FEATURE_SET_MAINDIAL
#undef FEATURE_PLAY_EXPOSURE_FUSION
#undef FEATURE_PLAY_COMPARE_IMAGES
#undef FEATURE_PLAY_TIMELAPSE
#undef FEATURE_PLAY_EXPOSURE_ADJUST
#undef FEATURE_IMAGE_REVIEW_PLAY
#undef FEATURE_QUICK_ZOOM
#undef FEATURE_LV_BUTTON_PROTECT
#undef FEATURE_LV_BUTTON_RATE
#undef FEATURE_LV_BUTTON_RATE_UPDOWN
#undef FEATURE_QUICK_ERASE
#undef FEATURE_LV_ZOOM_SETTINGS
#undef FEATURE_LV_ZOOM_SHARP_CONTRAST
#undef FEATURE_LV_ZOOM_AUTO_EXPOSURE
#undef FEATURE_ZOOM_TRICK_5D3
#undef FEATURE_LV_FOCUS_BOX_FAST
#undef FEATURE_LV_FOCUS_BOX_SNAP
#undef FEATURE_LV_FOCUS_BOX_SNAP_TO_X5_RAW
#undef FEATURE_LV_FOCUS_BOX_AUTOHIDE
#undef FEATURE_ARROW_SHORTCUTS
#undef FEATURE_STICKY_DOF
#undef FEATURE_STICKY_HALFSHUTTER
#undef FEATURE_SWAP_MENU_ERASE
#undef FEATURE_SWAP_INFO_PLAY
#undef FEATURE_WARNINGS_FOR_BAD_SETTINGS
#undef FEATURE_POWERSAVE_LIVEVIEW
#undef FEATURE_LV_DISPLAY_PRESETS
#undef FEATURE_EYEFI_TRICKS
#undef FEATURE_KEN_ROCKWELL_ZOOM_5D3
#undef FEATURE_DIGITAL_ZOOM_SHORTCUT
#undef FEATURE_FLEXINFO
#undef FEATURE_DONT_CLICK_ME
#undef FEATURE_SHOW_TASKS
#undef FEATURE_SHOW_CPU_USAGE
#undef FEATURE_SHOW_GUI_EVENTS
#undef FEATURE_SHOW_IMAGE_BUFFERS_INFO
#undef FEATURE_SHOW_FREE_MEMORY
#undef FEATURE_SHOW_SHUTTER_COUNT
#undef FEATURE_SHOW_CMOS_TEMPERATURE
#undef FEATURE_SHOW_EDMAC_INFO
#undef FEATURE_SHOW_SIGNATURE
#undef FEATURE_GUIMODE_TEST
#undef FEATURE_SHOW_STATE_FPS
