# define the module name - make sure name is max 8 characters
MODULE_NAME = cf_acc
MODULE_OBJS = $(BUILD_DIR)/cf_acc.o
TOP_DIR = ../..

# include modules environment
include $(TOP_DIR)/modules/Makefile
.DEFAULT_GOAL := $(BUILD_DIR)/module_complete
