CFLAGS += -DCONFIG_STATIC_FONTS=1

#ML_INSTALLER_BUILD_FIR= python ../../../dumper/build_fir7.py -r -i 0x301 -s updater.bin ../../../dumper/5D300113.FIR 650D_101.fir

MODEL=650D
include ../Makefile.installer
