TOP_DIR?=../..
ML_SETUP_EXTENSION=platform
ML_SRC_PROFILE?=generic

include $(TOP_DIR)/platform/Makefile.platform.base

install:: autoexec.bin
	$(CP) autoexec.bin $(INSTALL_DIR)/

include $(TOP_DIR)/Makefile.inc

# tag any function with DUMP_ASM, then run "make dump_asm" from platform/CAM directory
dump_asm: all
	$(OBJDUMP) -d -M reg-names-raw --section=.dump_asm magiclantern
