/***
 Constants
 
 @author Magic Lantern Team
 @copyright 2014
 @license GPL
 @module constants
 */

#include <dryos.h>
#include <bmp.h>
#include <menu.h>
#include <property.h>

#include "lua_common.h"

/// Camera shooting mode
// @field P
// @field TV
// @field AV
// @field M
// @field BULB
// @field ADEP
// @field C
// @field C2
// @field C3
// @field CA
// @field AUTO
// @field NOFLASH
// @field PORTRAIT
// @field LANDSCAPE
// @field MACRO
// @field SPORTS
// @field NIGHT
// @field MOVIE
// @table MODE
int luaopen_MODE(lua_State * L)
{
    lua_newtable(L);
    LUA_CONSTANT(P, SHOOTMODE_P);
    LUA_CONSTANT(TV, SHOOTMODE_TV);
    LUA_CONSTANT(AV, SHOOTMODE_AV);
    LUA_CONSTANT(M, SHOOTMODE_M);
    LUA_CONSTANT(BULB, SHOOTMODE_BULB);
    LUA_CONSTANT(ADEP, SHOOTMODE_ADEP);
    LUA_CONSTANT(C, SHOOTMODE_C);
    LUA_CONSTANT(C2, SHOOTMODE_C2);
    LUA_CONSTANT(C3, SHOOTMODE_C3);
    LUA_CONSTANT(CA, SHOOTMODE_CA);
    LUA_CONSTANT(AUTO, SHOOTMODE_AUTO);
    LUA_CONSTANT(NOFLASH, SHOOTMODE_NOFLASH);
    LUA_CONSTANT(PORTRAIT, SHOOTMODE_PORTRAIT);
    LUA_CONSTANT(LANDSCAPE, SHOOTMODE_LANDSCAPE);
    LUA_CONSTANT(MACRO, SHOOTMODE_MACRO);
    LUA_CONSTANT(SPORTS, SHOOTMODE_SPORTS);
    LUA_CONSTANT(NIGHT, SHOOTMODE_NIGHT);
    LUA_CONSTANT(MOVIE, SHOOTMODE_MOVIE);
    return 1;
}

/// Menu icon type
// @field AUTO
// @field BOOL
// @field DICE
// @field PERCENT
// @field ALWAYS_ON
// @field ACTION
// @field BOOL_NEG
// @field DISABLE_SOME_FEATURE
// @field SUBMENU
// @field DICE_OFF
// @field PERCENT_OFF
// @field PERCENT_LOG
// @field PERCENT_LOG_OFF
// @table ICON_TYPE
int luaopen_ICON_TYPE(lua_State * L)
{
    lua_newtable(L);
    LUA_CONSTANT(AUTO, IT_AUTO);
    LUA_CONSTANT(BOOL, IT_BOOL);
    LUA_CONSTANT(DICE, IT_DICE);
    LUA_CONSTANT(PERCENT, IT_PERCENT);
    LUA_CONSTANT(ALWAYS_ON, IT_ALWAYS_ON);
    LUA_CONSTANT(ACTION, IT_ACTION);
    LUA_CONSTANT(BOOL_NEG, IT_BOOL_NEG);
    LUA_CONSTANT(DISABLE_SOME_FEATURE, IT_DISABLE_SOME_FEATURE);
    LUA_CONSTANT(SUBMENU, IT_SUBMENU);
    LUA_CONSTANT(DICE_OFF, IT_DICE_OFF);
    LUA_CONSTANT(PERCENT_OFF, IT_PERCENT_OFF);
    LUA_CONSTANT(PERCENT_LOG, IT_PERCENT_LOG);
    LUA_CONSTANT(PERCENT_LOG_OFF, IT_PERCENT_LOG_OFF);
    return 1;
}

/// Menu value unit
// @field EV
// @field x10
// @field PERCENT
// @field PERCENT_x10
// @field ISO
// @field HEX
// @field DEC
// @field TIME
// @table UNIT
int luaopen_UNIT(lua_State * L)
{
    lua_newtable(L);
    LUA_CONSTANT(EV, UNIT_1_8_EV);
    LUA_CONSTANT(x10, UNIT_x10);
    LUA_CONSTANT(PERCENT, UNIT_PERCENT);
    LUA_CONSTANT(PERCENT_x10, UNIT_PERCENT_x10);
    LUA_CONSTANT(ISO, UNIT_ISO);
    LUA_CONSTANT(HEX, UNIT_HEX);
    LUA_CONSTANT(DEC, UNIT_DEC);
    LUA_CONSTANT(TIME, UNIT_TIME);
    return 1;
}

/// Dependency for a menu item
// @field GLOBAL_DRAW
// @field LIVEVIEW
// @field NOT_LIVEVIEW
// @field MOVIE_MODE
// @field PHOTO_MODE
// @field AUTOFOCUS
// @field MANUAL_FOCUS
// @field CFN_AF_HALFSHUTTER
// @field CFN_AF_BACK_BUTTON
// @field EXPSIM
// @field NOT_EXPSIM
// @field CHIPPED_LENS
// @field M_MODE
// @field MANUAL_ISO
// @field SOUND_RECORDING
// @field NOT_SOUND_RECORDING
// @table DEPENDS_ON
int luaopen_DEPENDS_ON(lua_State * L)
{
    lua_newtable(L);
    LUA_CONSTANT(GLOBAL_DRAW, DEP_GLOBAL_DRAW);
    LUA_CONSTANT(LIVEVIEW, DEP_LIVEVIEW);
    LUA_CONSTANT(NOT_LIVEVIEW, DEP_NOT_LIVEVIEW);
    LUA_CONSTANT(MOVIE_MODE, DEP_MOVIE_MODE);
    LUA_CONSTANT(PHOTO_MODE, DEP_PHOTO_MODE);
    LUA_CONSTANT(AUTOFOCUS, DEP_AUTOFOCUS);
    LUA_CONSTANT(MANUAL_FOCUS, DEP_MANUAL_FOCUS);
    LUA_CONSTANT(CFN_AF_HALFSHUTTER, DEP_CFN_AF_HALFSHUTTER);
    LUA_CONSTANT(CFN_AF_BACK_BUTTON, DEP_CFN_AF_BACK_BUTTON);
    LUA_CONSTANT(EXPSIM, DEP_EXPSIM);
    LUA_CONSTANT(NOT_EXPSIM, DEP_NOT_EXPSIM);
    LUA_CONSTANT(CHIPPED_LENS, DEP_CHIPPED_LENS);
    LUA_CONSTANT(M_MODE, DEP_M_MODE);
    LUA_CONSTANT(MANUAL_ISO, DEP_MANUAL_ISO);
    LUA_CONSTANT(SOUND_RECORDING, DEP_SOUND_RECORDING);
    LUA_CONSTANT(NOT_SOUND_RECORDING, DEP_NOT_SOUND_RECORDING);
    return 1;
}

/// Fonts
// @field MONO_12
// @field MONO_20
// @field SANS_23
// @field SANS_28
// @field SANS_32
// @field CANON
// @field SMALL
// @field MED
// @field MED_LARGE
// @table FONT
int luaopen_FONT(lua_State * L)
{
    lua_newtable(L);
    LUA_CONSTANT(MONO_12, FONT_MONO_12);
    LUA_CONSTANT(MONO_20, FONT_MONO_20);
    LUA_CONSTANT(SANS_23, FONT_SANS_23);
    LUA_CONSTANT(SANS_28, FONT_SANS_28);
    LUA_CONSTANT(SANS_32, FONT_SANS_32);
    LUA_CONSTANT(CANON, FONT_CANON);
    LUA_CONSTANT(SMALL, FONT_SMALL);
    LUA_CONSTANT(MED, FONT_MED);
    LUA_CONSTANT(MED_LARGE, FONT_MED_LARGE);
    return 1;
}

/// Color palatte
// @field TRANSPARENT
// @field WHITE
// @field BLACK
// @field TRANSPARENT_BLACK
// @field CYAN
// @field GREEN1
// @field GREEN2
// @field RED
// @field LIGHT_BLUE
// @field BLUE
// @field DARK_RED
// @field MAGENTA
// @field YELLOW
// @field ORANGE
// @field ALMOST_BLACK
// @field ALMOST_WHITE
// @field DARK_GREEN1_MOD
// @field DARK_GREEN2_MOD
// @field DARK_ORANGE_MOD
// @field DARK_CYAN1_MOD
// @field DARK_CYAN2_MOD
// @table COLOR
int luaopen_COLOR(lua_State * L)
{
    lua_newtable(L);
    LUA_CONSTANT(TRANSPARENT, COLOR_EMPTY);
    LUA_CONSTANT(WHITE, COLOR_WHITE);
    LUA_CONSTANT(BLACK, COLOR_BLACK);
    LUA_CONSTANT(TRANSPARENT_BLACK, COLOR_TRANSPARENT_BLACK);
    LUA_CONSTANT(CYAN, COLOR_CYAN);
    LUA_CONSTANT(GREEN1, COLOR_GREEN1);
    LUA_CONSTANT(GREEN2, COLOR_GREEN2);
    LUA_CONSTANT(RED, COLOR_RED);
    LUA_CONSTANT(LIGHT_BLUE, COLOR_LIGHT_BLUE);
    LUA_CONSTANT(BLUE, COLOR_BLUE);
    LUA_CONSTANT(DARK_RED, COLOR_DARK_RED);
    LUA_CONSTANT(MAGENTA, COLOR_MAGENTA);
    LUA_CONSTANT(YELLOW, COLOR_YELLOW);
    LUA_CONSTANT(ORANGE, COLOR_ORANGE);
    LUA_CONSTANT(ALMOST_BLACK, COLOR_ALMOST_BLACK);
    LUA_CONSTANT(ALMOST_WHITE, COLOR_ALMOST_WHITE);
    LUA_CONSTANT(DARK_GREEN1_MOD, COLOR_DARK_GREEN1_MOD);
    LUA_CONSTANT(DARK_GREEN2_MOD, COLOR_DARK_GREEN2_MOD);
    LUA_CONSTANT(DARK_ORANGE_MOD, COLOR_DARK_ORANGE_MOD);
    LUA_CONSTANT(DARK_CYAN1_MOD, COLOR_DARK_CYAN1_MOD);
    LUA_CONSTANT(DARK_CYAN2_MOD, COLOR_DARK_CYAN2_MOD);
    return 1;
}