#define FEATURE_SCREENSHOT
#define FEATURE_SCREENSHOT_422

#define FEATURE_DONT_CLICK_ME

#define FEATURE_SHOW_TASKS
#define FEATURE_SHOW_CPU_USAGE

#define FEATURE_SHOW_IMAGE_BUFFERS_INFO
#define FEATURE_SHOW_FREE_MEMORY
#define FEATURE_SHOW_SHUTTER_COUNT
#define FEATURE_SHOW_CMOS_TEMPERATURE

#define FEATURE_SNAP_SIM


#define FEATURE_GLOBAL_DRAW
#define FEATURE_ZEBRA
#define FEATURE_ZEBRA_FAST
#define FEATURE_FOCUS_PEAK
//~ #define FEATURE_FOCUS_PEAK_DISP_FILTER // too slow
#define FEATURE_MAGIC_ZOOM
#define FEATURE_CROPMARKS
#define FEATURE_GHOST_IMAGE
#define FEATURE_SPOTMETER
#define FEATURE_FALSE_COLOR
#define FEATURE_HISTOGRAM
#define FEATURE_WAVEFORM
#define FEATURE_VECTORSCOPE