#define FEATURE_SCREENSHOT
#define FEATURE_SCREENSHOT_422

#define FEATURE_DONT_CLICK_ME

#define FEATURE_SHOW_TASKS
#define FEATURE_SHOW_CPU_USAGE

#define FEATURE_SHOW_IMAGE_BUFFERS_INFO
#define FEATURE_SHOW_FREE_MEMORY
#define FEATURE_SHOW_SHUTTER_COUNT
#define FEATURE_SHOW_CMOS_TEMPERATURE

#define FEATURE_SNAP_SIM