// for early porting
#undef CONFIG_CRASH_LOG
#undef CONFIG_PROP_REQUEST_CHANGE
#undef CONFIG_AUTOBACKUP_ROM

#define CONFIG_TASK_ATTR_STRUCT_V2
#define CONFIG_TASK_STRUCT_V2
#define CONFIG_ALLOCATE_MEMORY_POOL
