# define the module name - make sure name is max 8 characters
MODULE_NAME = file_man
MODULE_OBJS = $(BUILD_DIR)/file_man.o
TOP_DIR = ../..

# include modules environment
include $(TOP_DIR)/modules/Makefile
.DEFAULT_GOAL := $(BUILD_DIR)/module_complete
