
# this is a very simple makefile for modules
TOP_DIR=$(PWD)/../..

# define the module name
MODULE_NAME = testmodule.mo
MODULE_OBJS = test.o

# include make environment
include $(TOP_DIR)/Makefile.top
include $(TOP_DIR)/Makefile.inc


