# define the module name - make sure name is max 8 characters
MODULE_NAME = mem_prot
MODULE_OBJS = $(BUILD_DIR)/mem_prot.o
TOP_DIR = ../../..

# include modules environment
include $(TOP_DIR)/modules/Makefile
.DEFAULT_GOAL := $(BUILD_DIR)/module_complete
