--- Makefile
+++ Makefile
@@ -217,9 +217,9 @@
         font-small.o \
         config.o \
         debug.o \
+        menu.o \
         stdio.o \
         audio.o \
-        menu.o \
         gui.o \
         property.o \
         zebra.o \
