
FW_VERSION=109
MODEL=60D

# magiclantern.lds script MUST be first
# entry.o MUST be second
# menu.o and debug.o must come before the modules
ML_OBJS-y = \
	magiclantern.lds \
	entry.o \
	boot-hack.o \
	platform/$(MODEL).$(FW_VERSION)/stubs.o \
	version.o \
	bmp.o \
	font-large.o \
	font-med.o \
	font-small.o \
	config.o \
	menu.o \
	debug.o \
	stdio.o \
	audio.o \
	bitrate.o \
	lens.o \
	property.o \
	propvalues.o \
	platform/$(MODEL).$(FW_VERSION)/gui.o \
	platform/$(MODEL).$(FW_VERSION)/misc.o \
	platform/$(MODEL).$(FW_VERSION)/lens.o \
	platform/$(MODEL).$(FW_VERSION)/cfn.o \
	zebra.o \
	shoot.o \
	focus.o \
	chdk-gui_draw.o \
	movtweaks.o \
	tweaks.o \
	my_memset.o \
	menuhelp.o \
	menuindex.o \

#include generic rules and definitions

include Makefile.inc

all: magiclantern.fir

# DryOSmemory map
# RESTARTSTART is selected to be just above the end of the bss
#
ROMBASEADDR		= 0xFF010000
RESTARTSTART		= 0x0005f000

#not used but...
FIRMWARE_ID		= 0x80000286

