#include "all_features.h"
/* Can't Be Implemented */

#define FEATURE_DIGITAL_ZOOM_SHORTCUT
#define FEATURE_LV_3RD_PARTY_FLASH
#define FEATURE_FLASH_TWEAKS
#define FEATURE_EYEFI_TRICKS

#define DEBUG_TASK_HOOK


#define FEATURE_INTERMEDIATE_ISO_PHOTO_DISPLAY

#undef FEATURE_FLEXINFO

//#undef FEATURE_SHOW_TASKS
//#undef FEATURE_SHOW_CPU_USAGE
//#undef FEATURE_SHOW_GUI_EVENTS

#undef FEATURE_SHOW_IMAGE_BUFFERS_INFO
#undef FEATURE_SHOW_EDMAC_INFO

#undef CONFIG_TSKMON
