# define the module name - make sure name is max 8 characters
MODULE_NAME = ime_std
MODULE_OBJS = $(BUILD_DIR)/ime_std.o
TOP_DIR = ../../..

# include modules environment
include $(TOP_DIR)/modules/Makefile
.DEFAULT_GOAL := $(BUILD_DIR)/module_complete
