# define the module name - make sure name is max 8 characters
MODULE_NAME = iso_test
MODULE_OBJS = $(BUILD_DIR)/iso_test.o
TOP_DIR = ../../..

# include modules environment
include $(TOP_DIR)/modules/Makefile
.DEFAULT_GOAL := $(BUILD_DIR)/module_complete
