montage AFP_HALF_LEFT.BMP    AFP_HALF_RIGHT.BMP    AFP_HALF_UP.BMP   AFP_HALF_DOWN.BMP   AFP_H.BMP \
		AFP_HALF_LEFT2.BMP   AFP_HALF_RIGHT2.BMP   AFP_HALF_UP2.BMP  AFP_HALF_DOWN2.BMP  AFP_V.BMP \
		AFP_HALF_LEFT3.BMP   AFP_HALF_RIGHT3.BMP   AFP_HALF_UP3.BMP  AFP_HALF_DOWN3.BMP  AFP_SQUARE.BMP \
		-tile 5x3 -geometry 196x110+10+18 -border 3x3 AFP.png

		#AFP_HALF_LEFT4.BMP   AFP_HALF_RIGHT4.BMP   AFP_HALF_UP4.BMP  AFP_HALF_DOWN4.BMP  AFP_CENTER.BMP \

mogrify -matte -bordercolor white -border 0x20 AFP.png

cp AFP.png ../AFP.png
