#include "all_features.h"

#define FEATURE_DIGITAL_ZOOM_SHORTCUT
#define FEATURE_LV_3RD_PARTY_FLASH
#define FEATURE_EYEFI_TRICKS


#define FEATURE_INTERMEDIATE_ISO_PHOTO_DISPLAY

#undef FEATURE_FLEXINFO
