#include "all_features.h"

#define FEATURE_SILENT_PIC_HIRES
#define FEATURE_DIGITAL_ZOOM_SHORTCUT_600D
#define FEATURE_LV_3RD_PARTY_FLASH
#define FEATURE_EYEFI_TRICKS

#undef FEATURE_AUTO_BURST_PICQ // not working on 600D

#define FEATURE_INTERMEDIATE_ISO_PHOTO_DISPLAY
