
// Auto-generated; do not edit this file.
// Edit doc/menuindex.py instead.

    {
        .name = "Important notes",
        .priv = "Important notes",
        .select = menu_help_go_to_label,
        .update = user_guide_display,
        .icon_type = IT_ACTION,
    },
    {
        .name = "Known issues",
        .priv = "Known issues",
        .select = menu_help_go_to_label,
        .update = user_guide_display,
        .icon_type = IT_ACTION,
    },
    {
        .name = "Common terms",
        .priv = "Common terms",
        .select = menu_help_go_to_label,
        .update = user_guide_display,
        .icon_type = IT_ACTION,
    },
    {
        .name = "Liveview screen layout",
        .priv = "Liveview screen layout",
        .select = menu_help_go_to_label,
        .update = user_guide_display,
        .icon_type = IT_ACTION,
    },
    {
        .name = "Key shortcuts",
        .priv = "Key shortcuts",
        .select = menu_help_go_to_label,
        .update = user_guide_display,
        .icon_type = IT_ACTION,
    },
    {
        .name = "Magic Lantern menu",
        .priv = "Magic Lantern menu",
        .select = menu_help_go_to_label,
        .update = user_guide_display,
        .icon_type = IT_ACTION,
    },
    {
        .name = "Epilogue",
        .priv = "Epilogue",
        .select = menu_help_go_to_label,
        .update = user_guide_display,
        .icon_type = IT_ACTION,
    },
