
// Auto-generated; do not edit this file.
// Edit doc/menuindex.py instead.

#include "dryos.h"
#include "version.h"
#include "bmp.h"
#include "menu.h"
#include "menuhelp.h"

struct menu_entry help_menus[] = {
    {
        .name = "About Magic Lantern",
        .priv = "About Magic Lantern",
        .select = menu_help_go_to_label,
        .display = menu_print,
        .essential = FOR_MOVIE | FOR_PHOTO,
    },
    {
        .name = "Important notes",
        .priv = "Important notes",
        .select = menu_help_go_to_label,
        .display = menu_print,
        .essential = FOR_MOVIE | FOR_PHOTO,
    },
    {
        .name = "FAQ",
        .priv = "FAQ",
        .select = menu_help_go_to_label,
        .display = menu_print,
        .essential = FOR_MOVIE | FOR_PHOTO,
    },
    {
        .name = "Known issues",
        .priv = "Known issues",
        .select = menu_help_go_to_label,
        .display = menu_print,
        .essential = FOR_MOVIE | FOR_PHOTO,
    },
    {
        .name = "Key shortcuts",
        .priv = "Key shortcuts",
        .select = menu_help_go_to_label,
        .display = menu_print,
        .essential = FOR_MOVIE | FOR_PHOTO,
    },
    {
        .name = "Magic Lantern menu",
        .priv = "Magic Lantern menu",
        .select = menu_help_go_to_label,
        .display = menu_print,
        .essential = FOR_MOVIE | FOR_PHOTO,
    },
    {
        .name = "Extra info displays",
        .priv = "Extra info displays",
        .select = menu_help_go_to_label,
        .display = menu_print,
        .essential = FOR_MOVIE | FOR_PHOTO,
    },
    {
        .name = "Power saving",
        .priv = "Power saving",
        .select = menu_help_go_to_label,
        .display = menu_print,
        .essential = FOR_MOVIE | FOR_PHOTO,
    },
    {
        .name = "Hidden settings",
        .priv = "Hidden settings",
        .select = menu_help_go_to_label,
        .display = menu_print,
        .essential = FOR_MOVIE | FOR_PHOTO,
    },
    {
        .name = "Epilogue",
        .priv = "Epilogue",
        .select = menu_help_go_to_label,
        .display = menu_print,
        .essential = FOR_MOVIE | FOR_PHOTO,
    },
};

static void
help_menu_init( void* unused )
{
	menu_add("Help", help_menus, COUNT(help_menus));
}

INIT_FUNC( "help_menu", help_menu_init );

int help_pages = 135;
int help_menus_num = 10;


