
// Auto-generated; do not edit this file.
// Edit doc/menuindex.py instead.

    {
        .name = "Important notes",
        .select = menu_help_go_to_label,
    },
    {
        .name = "Known issues",
        .select = menu_help_go_to_label,
    },
    {
        .name = "Common terms",
        .select = menu_help_go_to_label,
    },
    {
        .name = "Liveview screen layout",
        .select = menu_help_go_to_label,
    },
    {
        .name = "Key shortcuts",
        .select = menu_help_go_to_label,
    },
    {
        .name = "Magic Lantern menu",
        .select = menu_help_go_to_label,
    },
