OS_FUNCTION( 1,		void,	msleep, int amount );
OS_FUNCTION( 2,		void,	bmp_printf, int font, int x, int y, const char* fmt, ... );
OS_FUNCTION( 3,		FILE*,	FIO_Open, const char* filename, int mode );
OS_FUNCTION( 4,		int,	FIO_ReadFile, FILE* stream, void* ptr, size_t count );
OS_FUNCTION( 5,		int,	console_vprintf, const char* fmt, ... );
OS_FUNCTION( 6,		void,	console_puts, const char* str );
OS_FUNCTION( 7,		int,	FIO_WriteFile, FILE* stream, const void* ptr, size_t count );
OS_FUNCTION( 8,		void,	FIO_CloseFile, FILE* stream );
OS_FUNCTION( 9,		int,	strlen, const char* str );
OS_FUNCTION( 10,	int,	vsnprintf, char* str, size_t n, const char* fmt, va_list ap );
OS_FUNCTION( 11,	void*,	AllocateMemory, size_t size );
OS_FUNCTION( 12,	void,	FreeMemory, void* ptr );
OS_FUNCTION( 13,	void,	my_memcpy, void* dst, const void* src, size_t size );
OS_FUNCTION( 14,	int,	strcmp, const char* s1, const char* s2 );
OS_FUNCTION( 15,	int,	abs, int number );
OS_FUNCTION( 16,	int,	strtol, const char * str, char ** endptr, int base );
OS_FUNCTION( 17,	char*,	strcpy, char* dst, const char * src );
