
# this is a very simple makefile for modules
TOP_DIR=../..

# define the module name - make sure name is max 8 characters
MODULE_NAME=hdmi_out
MODULE_OBJS=hdmi_out.o
MODULE_CFLAGS += -Wno-switch

# include modules environment
include $(TOP_DIR)/modules/Makefile.modules
