#define FEATURE_VRAM_RGBA

//enable FEATURE_COMPOSITOR_XCM only in full build
#ifndef ML_MINIMAL_OBJ
#define FEATURE_COMPOSITOR_XCM
#endif

#define CONFIG_ADDITIONAL_VERSION
#define FEATURE_SCREENSHOT


#undef CONFIG_CRASH_LOG
#undef CONFIG_TSKMON
#undef CONFIG_PROP_REQUEST_CHANGE
#undef CONFIG_AUTOBACKUP_ROM
