
# this is a very simple makefile for modules
TOP_DIR=../..

# define the module name - make sure name is max 8 characters
MODULE_NAME=crop_rec
MODULE_OBJS=crop_rec.o
MODULE_CFLAGS += -Wno-switch

# include modules environment
include $(TOP_DIR)/modules/Makefile.modules
