
TOP_DIR?=../..
ML_SETUP_DISABLE_USER_CONFIGS=y
ML_SETUP_EXTENSION=installer
ML_SRC_PROFILE=installer

include $(TOP_DIR)/platform/Makefile.platform.base

installer:: build_fir

install:: install_fir

clean::
	$(call rm_files, updater*)

include $(TOP_DIR)/Makefile.inc
